### ISSUE TITLE
Similar error

### ISSUE THREAD

**Issue by curious-mike-dvc** [facundoolano/app-store-scraper#121]
* Operating System: Windows 10
* Node version: v10.15.3
* app-play-scraper version: "^0.16.2"

### Description: 
I get this error when running the same code as in documentation (and changing app id does not help).

### Example code:
store.similar({id: 553834731}).then(console.log).catch(console.log);

### Error message:
 TypeError: Cannot read property '0' of null
[0]     at \node_modules\app-store-scraper\lib\similar.js:30:69
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by curious-mike-dvc** [comment]
As noticed with #114 it is fixed. Perhaps you could release a new version ?
