### ISSUE TITLE
similar queries are failing

### ISSUE THREAD

**Issue by rchatterjee** [facundoolano/app-store-scraper#127]
* Operating System: Linux
* Node version: v12.16.1
* app-play-scraper version: 0.16.2

### Description: 
The `similar` queries are failing. 

### Example code:
```js
// Put code to reproduce the issue here
var store = require('app-store-scraper');
store.similar({id: 553834731}).then(console.log).catch(console.log)
```

### Error message:

```
Promise { <pending> }
> TypeError: Cannot read property '0' of null
    at /home/ubuntu/appscraper/scraper/node_modules/app-store-scraper/lib/similar.js:30:69
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rchatterjee** [comment]
Ahh, I see there is a new fix already on the master branch, waiting to be published.
