### ISSUE TITLE
Crash when single review is returned

### ISSUE THREAD

**Issue by deze333** [facundoolano/app-store-scraper#83]
If there is only one review then the server returns a single object, not an array and the parser crashes with:

```
TypeError: reviews.map is not a function
    at cleanList (.../node_modules/app-store-scraper/lib/reviews.js:15:18)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Try this call to duplicate:

```javascript
store.reviews({id:` 1092841332, country: 'IL'}).then(console.log).catch(console.log);
```

Error is here:
```javascript
function cleanList (results) {
  let reviews = results.feed.entry || [];
  return reviews.map((review) => ({
// ...
```

I managed to fix the problem with something like the code below but perhaps there could be a better way.

```javascript
function cleanList (results) {
  let reviews = results.feed.entry || [];
  // Check if it's a single object and if so wrap it into array
  if (results.feed.entry && !Array.isArray(results.feed.entry)) {
    reviews = [results.feed.entry];
  }
  return reviews.map((review) => ({
// ...
```

**Comment by facundoolano** [comment]
this has been fixed in #89
